### PR TITLE
Upgrade go.

### PR DESCRIPTION
**Pull request by Tang8330**
Upgrading Go to address CVEs stemming from `stdlib`

### CODE REVIEW

**Comment by alerque** [comment]
Do the CVEs *really* affect this app or do they just happen to exist in an unrelated/unused API surface in Go?

**Comment by Tang8330** [comment]
image

Not sure, but given it's just a Go upgrade, I don't see why we wouldn't just address them.

**Comment by alerque** [comment]
At least one of those has already been brought up here: https://github.com/FiloSottile/age/pull/409#issuecomment-1103827329.

The more general point of "why not just bump" is also addressed in places like here: https://github.com/FiloSottile/age/pull/458#issuecomment-1292662263.

**Comment by Tang8330** [comment]
I understand the position of not wanting to bump for the sake of bumping a CVE that may not actually impact age, thus generating busywork.

However, how do you plan to actually tackle triaging to ensure that appropriate CVEs are being addressed and providing a rationale for why particular CVEs that have been flagged are being purposefully ignored?

**Comment by FiloSottile** [comment]
None of those affect packages that are reachable from this project, so there is nothing to triage.

```
$ govulncheck ./...
=== Symbol Results ===

No vulnerabilities found.

Your code is affected by 0 vulnerabilities.
```

See https://filippo.io/maintenance#on-security-scanners. Please use a better scanner.

**Pull request closed without merging**
