### PR TITLE
Add --version and --help flags to executables

### LINKED ISSUE #74: UX: Show usage on naked command
## What were you trying to do

Show the usage documentation.

## What happened

```
$ age
Error: missing recipients.
Did you forget to specify -r/--recipient or -p/--passphrase?
[ Did age not do what you expected? Could an error be more useful? Tell us: https://filippo.io/age/report ]
```

## Additional detail

Right after installing age, most people are going want to see the usage output. It makes for a better user experience if you show the usage / help for all things that the user might try, instead of making the user try multiple different flags to get the usage to appear.

I'd suggest displaying the usage output when age is run with any of the following arguments:

- `age`
- `age help`
- `age --help`
- `age -h`

### LINKED ISSUE #101: UX: What version of age am I running?
How can I know what version of age I'm using? There doesn't seem to be any `-version` flag.

### PR DESCRIPTION
**Pull request by RKinsey**
Closes #74 , Closes #101 
This patch adds flags for access to the usage message and the version tag/hash as requested in #74 and #57, respectively.  

`age` and `age-keygen` with the `--help` or `-h` flag will print their usage message and exit, and `age` will also print usage when no flags or arguments are passed. Per #22, I didn't add `age help`.    
`age-keygen` now has a usage message.  

~~`-v` and~~ (Removed, see below) `--version` work for both `age` and `age-keygen`, and will print the most recent git info at time of compilation. There are two build scripts (bash and Powershell) that grab the most recent tag and current short hash, and uses -ldflags to pass them to main.version and main.commit (named for compatibility with goreleaser defaults). Current format is  
``` 
Version: [most recent tag]
Hash: [shorthash] 
```   
and  
`Version: [most recent tag]` when on a tagged commit or the --release flag is passed to the script.  
I also updated the Homebrew formula for this, but it doesn't currently have an effect

### CODE REVIEW

**Comment by wgslr** [comment]
I'm glad to see you implemented my proposal. Just one note: I would be wary of using the `-v` flag for `--version`, as it is often used for `--verbose` and I could image `age` adding such flag in the future. I suggest either using `-V` or not providing a short flag at all, as the version invocation is done rarely and does not need to be particularly compact.

**Comment by RKinsey** [comment]
Good point, removed `-v`

**Comment by alerque** [comment]
@RKinsey I think you can also add `Closes #101` to this issue description.

**Comment by RKinsey** [comment]
Got it

**Comment by Fastidious** [comment]
Would be great if this PR could be accepted. What say you, @FiloSottile? :-)

**Comment by brad2014** [comment]
Just a thought: There are two relevant version strings related to the `age` app: the release version of the code (currently "v1.0.0-beta2") and the version(s) of the supported file spec (currently "v1", but a later release might support multiple file specs).

Do you want to consider wording the `age --help` and the `age --version` output to distinguish between these two uses of the word version?  Maybe:

```
% age --version 
Release version: 1.0.0-beta2
Age spec version: v1
```

**Comment by shepting** [comment]
I'd love to see this land! Any updates @RKinsey

**Comment by FiloSottile** [comment]
Most users will eventually use `go install filippo.io/age/cmd/...@latest` (which from Go 1.16 embeds the version) or Homebrew or a package manager, so I took a slightly simpler path in #173. Thank you!

@brad2014 that's a good point, but we don't plan to ever drop support for older versions of the spec, so for now I think it's fine not to expose it.

**Comment by ank-everstake** [comment]
I think it may be better to expose info for debug purposes.
User can open age-encrypted file on another machine with different age-binary. 
So basically if we hide it we don't have any option to know what binary the user has. 
You can compile by yourself, get pre-built binaries or get them through pacman AUR (in Arch).
Please consider to add the version back. Thanks.

CC @dd-everstake

**Pull request closed without merging**
