### PR TITLE
doc: fix typo

### PR DESCRIPTION
**Pull request by andreaswachowski**

### CODE REVIEW

**Comment by FiloSottile** [comment]
Thank you! You can drop the roff and html changes, they are autogenerated files.

**Comment by andreaswachowski** [comment]
Ah, of course, I should have looked closer at the manpage-PR. Done. Thanks for the great tool and hard work on age!

**Comment by alerque** [comment]
> You can drop the roff and html changes, they are autogenerated files.

Why are they tracked in Git if they are autogenerated? Shouldn't they just be part of the build process for where they are needed?

**Comment by FiloSottile** [comment]
Thank you @andreaswachowski! ✨

**Pull request merged**
