### PR TITLE
separate public/private key files

### LINKED ISSUE #91: UX: separate public/private key files
## What were you trying to do

Sharing the public key.

## What happened

I needed to open the file and copy-paste the public key characters in order to share the public key. Having a separate file for the public key would make it more easy for me to share using standard tools, avoids copy-pasting user errors and avoids shoulder surfing issues.

### PR DESCRIPTION
**Pull request by downneck**
Closes #91 
"age-keygen" with no flags will generate ~/.age/me.pub and ~/.age/me.key
"age-keygen -o filename" now generates ~/.age/filename.pub and ~/.age/filename.key
"age -d" will load ~/.age/*.key as well as ~/.ssh/id_rsa and ~/.ssh/id_ed25519
"age -r me" will encrypt using the key found in ~/.age/me.pub
"age -r marysmith" will encrypt using the key found in ~/.age/marysmith.pub

### CODE REVIEW

**Comment by str4d** [comment]
You should use `~/.config/age` to match the spec regarding age user data storage. See also #15.

**Comment by downneck** [comment]
@str4d thanks! updated.

**Comment by alxiong** [comment]
I'm wondering whether all pub keys should be put into a single file with annotated alias or should they be in separate files

@FiloSottile already had a proposal in his doc:
> Encryption to an alias (stored at ~/.config/age/aliases.txt, change with -aliases)
$ cat ~/.config/age/aliases.txt
filippo: pubkey:jqmfMHBjlb7HoIjjTsCQ9NHIk_q53Uy_ZxmXBhdIpx4
ben: pubkey:ZAE2ZnRdItykp0ncAZJ2FAzIIfTvmGcgIx/759QhnQw github:Benjojo
$ tar cv ~/xxx | age -r alias:filippo > xxx.tar.age

I feel that combing the _alias_ approach is more concise and easier for #110 (if applicable). 

If so, then `age-keygen -a myalias` would _append_ an entry in `~/.config/age/aliases.txt` and putting private key in `~/.config/age/myalias.key`

**Comment by FiloSottile** [comment]
We went through a few different ideas for how to add these conveniences, but ultimately none of them felt right because age is meant to be an explicit tool without opinions on how keys are exchanged or managed.

We ended up removing aliases, as well as default identities, and we don't have a `.config` path anymore. Applications and users should manage keys as they prefer.

**Comment by angelacastaneda** [comment]
for anyone missing the conveniences of default keys, I made a [shell script](https://gist.github.com/angelacastaneda/c700019600d745698acc028f9f8bac97) that tries to emulate the gpg experience.

i.e.

* `age -e <file>` produce an ascii armored <file>.age file in the same directory encrypted with the `$age_def_rec` file
* `age -d <file>` decrypts the file to stdout with the `$age_def_id` file
* anything that's not a file or doesn't uses -e/-d flags gets sent to the proper age binary location at `$age_bin`

**Pull request closed without merging**
